[package]
name = "sooqa-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
sooqa-api = { path = "../../crates/api" }
sooqa-config = { path = "../../crates/config" }
sooqa-runtime = { path = "../../crates/runtime" }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
