[package]
name = "sooqa-telegram"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
sooqa-library = { path = "../library" }
sooqa-media = { path = "../media" }
teloxide.workspace = true
thiserror.workspace = true
tokio.workspace = true
time.workspace = true
tracing.workspace = true
reqwest.workspace = true
uuid.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
time.workspace = true

[lints]
workspace = true
