[package]
name = "sooqa-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
sooqa-inbox = { path = "../inbox" }
sooqa-jobs = { path = "../jobs" }
sooqa-library = { path = "../library" }
sooqa-media = { path = "../media" }
sooqa-publisher = { path = "../publisher" }
sooqa-config = { path = "../config" }
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
time.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
